const SUCCESS_CODE = 201;
const ERROR_VALIDATION = 400;
const ERROR_AUTHORIZATION = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_CONFLICT = 409;
const ERROR_UNEXPECTED = 500;
const SAME_OBJECT_CODE = 11000;

module.exports = {
  ERROR_UNEXPECTED,
  ERROR_VALIDATION,
  ERROR_NOT_FOUND,
  ERROR_AUTHORIZATION,
  ERROR_FORBIDDEN,
  ERROR_CONFLICT,
  SUCCESS_CODE,
  SAME_OBJECT_CODE,
};
